services:
  autodeploytest:
    image: ghcr.io/yigdo/autodeploy-test:prod
    environment:
      - PORT:3030
    ports:
      - "3030:3030"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"