services:
  autodeploytest:
    image: ghcr.io/yigdo/auto-deploy-test:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PORT:3030
    ports:
      - "3030:3030"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"